apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-log
spec:
  volumeName: exercise-1-11-pv
  storageClassName: exercise-1-11-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
