FROM python:3.12-alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev

COPY src/backend.py .

ENV PORT=8001

RUN pip install --no-cache-dir \
    flask \
    requests \
    psycopg2-binary

EXPOSE 8001

CMD ["python", "backend.py"]

